name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install platform
      run: rustup target add thumbv7em-none-eabihf
    - name: Build
      run: cargo build --verbose

